name: Clang-Tidy

on:
  pull_request:
    branches: [ main ]
    paths: [ '**.c', '**.cpp', '**.h', '**.hpp' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tidy:
    name: Clang-Tidy
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' ||  github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Prepare compile_commands.json
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Create results directory
        run: |
          mkdir clang-tidy-result
      - name: Analyze
        run: |
          set -o pipefail
          git diff -U0 HEAD^ | clang-tidy-diff -p1 -path build -export-fixes clang-tidy-result/fixes.yml
      - name: Save PR metadata
        run: |
          echo ${{ github.event.number }} > clang-tidy-result/pr-id.txt
          echo ${{ github.event.pull_request.head.repo.full_name }} > clang-tidy-result/pr-head-repo.txt
          echo ${{ github.event.pull_request.head.ref }} > clang-tidy-result/pr-head-ref.txt
      - uses: actions/upload-artifact@v2
        with:
          name: clang-tidy-result
          path: clang-tidy-result/
          if-no-files-found: error
