name: Code style check

on: [ pull_request ]
jobs:
  check:
    name: Code style check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Install dependencies and clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-12
      - name: Setup clang-format
        run: |
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 200
          sudo update-alternatives --install /usr/bin/clang-format-diff clang-format-diff /usr/bin/clang-format-diff-12 200
      - name: Run clang-format-diff
        run: bash ./scripts/tools/check_code_format.sh