name: Linux-arm64

on: [ pull_request ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC
            os: ubuntu-raspberry_pi_4
    name: CMake (${{ matrix.config.name }})
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCERBERUS_STRICT_COMPILATION=ON -DUSE_LIBCPP=OFF
          cmake --build build -- -j4
          cd build
          ctest
          cd ..
