name: Linux-amd64

on: [ pull_request ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC
            os: [ self-hosted, linux, X64 ]
    name: CMake (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCERBERUS_STRICT_COMPILATION=ON -DUSE_LIBCPP=OFF
          cmake --build build -- -j1
      - name: Test
        run: |
          cd build
          ctest
          cd ..